#!/bin/sh

alias \
	ezp="nvim ${HOME}/.zprofile" \
	ezal="nvim ${ZDOTDIR}/aliasrc" \
	ezsht="nvim ${ZDOTDIR}/shortcutrc" \
	ezshv="nvim ${ZDOTDIR}/.zshenv" \
	ezrc="nvim ${ZDOTDIR}/.zshrc" \
	ehyp="nvim ${XDG_CONFIG_DIR}/hypr/" \

alias \
	cac="lfrun ${HOME}/.cache" \
	utp="lfrun ${HOME}/GameEngines/Unity/Projects" \
	cf="lfrun ${HOME}/.config" \
	cfz="lfrun ${HOME}/.config/shell" \
	dw="lfrun ${HOME}/Downloads" \
	dc="lfrun ${HOME}/Documents" \
	scb="lfrun ${HOME}/.local/bin " \
	src="lfrun ${HOME}/.local/src " \
	cfdw="lfrun ~/.local/src/dwm/" \
	cfnv="lfrun ${HOME}/.config/nvim/" \
