[package]
name = "paru"
version = "2.0.1"
authors = ["morganamilo <morganamilo@archlinux.org>"]
edition = "2021"

description = "Feature packed AUR helper"
homepage = "https://github.com/Morganamilo/paru"
repository = "https://github.com/Morganamilo/paru"
documentation = "https://docs.rs/paru"
license = "GPL-3.0"
keywords = ["archlinux", "arch", "alpm", "pacman", "aur"]
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md", "help"]


[dependencies]
alpm = "2.2.2"
alpm-utils = "2.0.0"
aur-depends = "3.0.0"
aur-fetch = "0.11.2"
cini = "1.0.0"
pacmanconf = "2.0.0"
raur = "7.0.0"
srcinfo = "1.1.0"


ansi_term = "0.12.1"
anyhow = { version = "1.0.75", features = ["backtrace"] }
chrono = { version = "0.4.31", default-features = false, features = ["clock"] }
dirs = "5.0.1"
futures = "0.3.29"
globset = "0.4.14"
htmlescape = "0.3.1"
indicatif = "0.17.7"
scraper = "0.18.1"
nix = { version = "0.27.1", features = ["fs", "user"] }
reqwest = { version = "0.11.22", features = ["gzip", "socks"] }
rss = { version = "2.0.6", default-features = false }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
smart-default = "0.7.1"
tempfile = "3.8.1"
terminal_size = "0.3.0"
tokio = { version = "1.34.0", features = [
    "process",
    "macros",
    "rt-multi-thread",
] }
url = "2.5.0"
env_logger = "0.10.1"
log = "0.4.20"
async-trait = { version = "0.1.74", optional = true }
tr = "0.1.7"
unicode-width = "0.1.11"
regex = "1.10.2"
signal-hook = "0.3.17"
once_cell = "1.18.0"
bitflags = "2.4.1"
toml = { version = "0.8.8", features = ["preserve_order"] }

[profile.release]
codegen-units = 1
lto = true

[features]
git = ["alpm/git", "alpm-utils/git", "aur-depends/git"]
backtrace = []
generate = ["alpm/generate"]
static = ["alpm/static"]
mock = ["async-trait"]
mock_chroot = ["mock"]
#default = ["git", "generate"]

[patch.crates-io]
#alpm = { path = "../alpm.rs/alpm" }
alpm = { git = "https://github.com/archlinux/alpm.rs", rev = "8da396" }
alpm-utils = { git = "https://github.com/archlinux/alpm.rs", rev = "8da396" }
#aur-depends = { path = "../aur-depends" }
aur-depends = { git = "https://github.com/Morganamilo/aur-depends", rev = "9f09f5"}
#aur-fetch = { path = "../aur-fetch" }
