live_config_reload = true

[scrolling]
history = 5000

[font]
size = 16

normal = { family = "InconsolataGo Nerd Font", style = "Regular" }
bold = { family = "InconsolataGo Nerd Font", style = "Bold" }
italic = { family = "InconsolataGo Nerd Font", style = "Italic" }
bold_italic = { family = "InconsolataGo Nerd Font", style = "Bold italic" }

builtin_box_drawing = false

[cursor]
style = { shape = "Block", blinking = "Never" }

#[keyboard]
#bindings = [{ 'Plus', 'Command', 'IncreaseFont' }]
#bindings = [{ 'Plus', 'Command', 'IncreaseFont' }]
